# install: conda env create -f conda_env.yaml
# update: conda env update -f conda_env.yaml --prune

name: behavysis_classifier_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - pip:
      - behavysis_classifier
